name: CI

on:
  push:
    branches:
      - main
  schedule:
    # Run every Wednesday, 1:56 PM UTC
    - cron: '56 13 * * 3'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip install ansible-lint[community,yamllint]

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian10
          - ubuntu2004
        ansible-version:
          - 2.9
          - 3
          - 4
        python-version:
          - 3.8
          - 3.9
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip3 install wheel
          pip3 install ansible==${{ matrix.ansible-version }}.* molecule[docker] docker yamllint ansible-lint
          ansible-galaxy collection install community.docker
          
      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
